# Generated by Django 2.2.3 on 2019-08-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsname', models.CharField(max_length=50)),
                ('goodsdesc', models.CharField(max_length=100)),
                ('goodsprice', models.CharField(max_length=5)),
                ('goodsnum', models.CharField(max_length=5)),
                ('goodsdetail', models.CharField(max_length=300)),
                ('goodsimg', models.FileField(upload_to='static/images')),
            ],
            options={
                'db_table': 't_goods',
            },
        ),
    ]
